In [2]:
import pandas as pd

In [6]:
df = pd.read_pickle('data/df')

In [7]:
df

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_76,feat_77,feat_78,feat_79,feat_80,feat_81,feat_82,feat_83,feat_84,marg
datetime,,,,,,,,,,,,,,,,,,,,,
2021-01-01 00:00:00+01:00,1.00,0.00,14946.845019,0.10,0.09,328.476120,71.47,0.000000,4503.082418,10389.003405,...,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,266.42,-196.42
2021-01-01 01:00:00+01:00,1.00,0.00,14243.407120,0.10,0.09,324.753360,70.66,0.000000,4361.306210,9829.394903,...,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,204.73,-134.73
2021-01-01 02:00:00+01:00,1.00,0.00,13722.977780,0.10,0.08,277.322640,60.34,0.000000,4185.773762,9471.930284,...,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,190.00,-40.00
2021-01-01 03:00:00+01:00,1.00,0.00,13726.786816,0.10,0.07,282.883800,61.55,0.000000,3908.972594,9773.339869,...,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,157.17,-7.17
2021-01-01 04:00:00+01:00,1.00,0.00,13827.919086,0.10,0.07,332.428680,72.33,0.000000,3800.952626,9985.306606,...,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,159.18,3.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-01 19:00:00+02:00,0.75,0.00,13260.975647,0.03,0.00,260.161059,60.33,21.904967,3277.231429,9961.839251,...,1956.0,7261.0,2737.0,1662.0,615.0,700.0,600.0,4979.0,361.24,-33.51
2023-04-01 20:00:00+02:00,0.74,0.00,13872.544003,0.03,0.01,257.444310,59.70,0.000000,3966.138937,9906.405066,...,1931.0,7258.0,2657.0,1662.0,615.0,700.0,600.0,5036.0,370.10,-36.27
2023-04-01 21:00:00+02:00,0.63,0.00,13684.481182,0.03,0.00,222.687172,51.64,0.000000,4438.532657,9245.948526,...,1929.0,7283.0,2657.0,1662.0,615.0,700.0,600.0,5036.0,343.20,-9.37
2023-04-01 22:00:00+02:00,0.60,0.05,13220.823731,0.03,0.00,232.562339,53.93,0.000000,4723.937196,8496.886536,...,1926.0,6698.0,2657.0,1662.0,615.0,700.0,600.0,5036.0,310.71,23.12
2023-04-01 23:00:00+02:00,0.75,0.06,12511.574813,0.04,0.00,219.366701,50.87,0.000000,4497.581872,8013.992942,...,1939.0,6700.0,2657.0,1662.0,615.0,700.0,600.0,5036.0,310.00,17.74

In [33]:
from mcut import AutoMCUT, mcut, mtrcs

def mcut_feature_selection(
        data,
        number_of_folds,
        target_variable,
        score_function,
        numb_of_bins,
        binning_func,
        how_many_folds,
        numb_of_best_features,
        numb_of_features_in_each_group,
        verbose=True,
        not_known=None,):
    m = AutoMCUT(data, number_of_folds, target_variable, score_function, numb_of_bins, binning_func, verbose, not_known)
    m.find_best_features( how_many_folds, numb_of_best_features, broad_df = False, numb_of_features_in_each_group = 5)
    return m.find_optimal_variables_lasso(numb_of_features_in_each_group)
# data

In [34]:
mcut_feature_selection(data, 2, 'marg', np.mean, 7, mcut, 0, 100, 5,)

Max condition is abs(mono)>0.5
Number of features is 56
I saved it as 'results'.
I saved importantn features due to the Lasso regression as an attribute 'important_features'.

['feat_66', 'feat_6', 'feat_50', 'feat_5', 'feat_75']

In [25]:
m.find_best_features(0,10,0)

Max condition is abs(mono)>0.5
Number of features is 56
I saved it as 'results'.
I saved importantn features due to the Lasso regression as an attribute 'important_features'.

In [26]:
m.find_optimal_variables_lasso(4)

['feat_50', 'feat_66', 'feat_5', 'feat_6']

In [21]:
X = df.drop('marg', axis=1)
y = df['marg']

In [ ]:
import pandas as pd
import statsmodels.api as sm
from IPython.display import clear_output

def forward_selection(data: pd.DataFrame):
    X = data.iloc[:,:-1]
    y = data.marg
    remaining_vars = list(X.columns)
    selected_vars = []
    current_score, best_new_score = 0.0, 0.0

    while remaining_vars and current_score == best_new_score:

        temp_results = pd.Series()
        for feat in remaining_vars:
            temp_feats = selected_vars + [feat]
            X_temp = X[temp_feats]
            X_temp = sm.add_constant(X_temp)
            model = sm.OLS(y, X_temp).fit()
            temp_results[feat] = model.rsquared_adj
            
        best_feature = temp_results.idxmax()
        best_new_score = temp_results.max()
        
        if current_score < best_new_score:
            remaining_vars.remove(best_feature)
            selected_vars.append(best_feature)
            current_score = best_new_score
            clear_output(wait=True)
            print(f'Current score: {current_score}')
            print(f'Selected features: {selected_vars}')
            
    return selected_vars

In [5]:
y = df.marg.copy()
data = df.loc[:, ~df.columns.str.contains('marg')]

In [6]:
new_cols = []
for i, col in enumerate(data.columns):
    new_cols.append('feat_' + str(i))
data.columns = new_cols

In [7]:
data['marg'] = y

In [8]:
# data.to_csv('clean_data.csv')

In [9]:
from mcut import AutoMCUT, mcut, mtrcs
import numpy as np
import pandas as pd
data = pd.read_csv('clean_data.csv', index_col=0)

c:\Users\mikol\Desktop\Master thesis\mcut_feature_selection\mcut_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
m = AutoMCUT(data, 4, 'marg', np.mean, 7, mcut)

In [3]:
m.find_best_features(0,10,False)

Max condition is abs(mono)>0.5
Number of features is 56
I saved it as 'results'.
I saved importantn features due to the Lasso regression as an attribute 'important_features'.

In [6]:
# write function that takes data, checks pearson correlations and return names with correlation in [-1,1]

def check_correlations(data):

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_75,feat_76,feat_77,feat_78,feat_79,feat_80,feat_81,feat_82,feat_83,marg
datetime,,,,,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00+01:00,1.00,0.00,14946.845019,0.10,0.09,328.476120,71.47,0.000000,4503.082418,10389.003405,...,150.0,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,-196.42
2022-01-01 01:00:00+01:00,1.00,0.00,14243.407120,0.10,0.09,324.753360,70.66,0.000000,4361.306210,9829.394903,...,150.0,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,-134.73
2022-01-01 02:00:00+01:00,1.00,0.00,13722.977780,0.10,0.08,277.322640,60.34,0.000000,4185.773762,9471.930284,...,150.0,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,-40.00
2022-01-01 03:00:00+01:00,1.00,0.00,13726.786816,0.10,0.07,282.883800,61.55,0.000000,3908.972594,9773.339869,...,150.0,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,-7.17
2022-01-01 04:00:00+01:00,1.00,0.00,13827.919086,0.10,0.07,332.428680,72.33,0.000000,3800.952626,9985.306606,...,150.0,1450.0,6500.0,2800.0,1700.0,315.0,700.0,600.0,4900.0,3.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-14 12:00:00+02:00,0.90,0.06,14465.680472,0.03,0.04,-12.014046,-2.82,4990.248492,7628.633749,1846.798231,...,500.0,186.0,4864.0,913.0,1662.0,519.0,700.0,600.0,3786.0,-30.00
2024-04-14 13:00:00+02:00,0.89,0.00,14300.580307,0.03,0.04,-12.014046,-2.82,4960.336501,7697.715814,1642.527992,...,500.0,186.0,4864.0,913.0,1662.0,519.0,700.0,600.0,3786.0,-30.00
2024-04-14 14:00:00+02:00,0.87,0.00,13776.317687,0.04,0.05,-12.014046,-2.82,4729.299709,7648.371481,1398.646497,...,500.0,186.0,4879.0,913.0,1662.0,519.0,700.0,600.0,3786.0,-30.00
2024-04-14 15:00:00+02:00,0.86,0.00,14167.633878,0.04,0.05,-12.014046,-2.82,4524.245869,7618.764882,2024.623127,...,500.0,186.0,4864.0,913.0,1662.0,519.0,700.0,600.0,3786.0,-35.00
2024-04-14 16:00:00+02:00,0.76,0.00,14386.388004,0.04,0.06,23.431650,5.50,3627.649052,7500.338485,3258.400467,...,500.0,186.0,4864.0,913.0,1662.0,519.0,700.0,600.0,3786.0,13.94

In [28]:
def check_correlations(data, how_many = 10):
    corr = data.corr()['marg']
    corr = corr[corr.index != 'marg']
    corr = corr.abs().sort_values(ascending=False)
    corr = corr.head(how_many)
    corr = corr.index
    return corr.tolist()

In [64]:
import statsmodels.api as sm
def RFE_feature_selection(data, accepted_p_value = 0.05):
    X = data.drop(columns='marg')
    X = sm.add_constant(X)
    y = data['marg']
    searching = True
    while searching:
        model = sm.OLS(y, X).fit()
        p_values = model.pvalues
        max_p = p_values.max()
        if max_p > accepted_p_value:
            X = X.drop(columns=p_values.idxmax())
        else:
            searching = False
    return X.columns.tolist(), model.summary()

In [65]:
x = RFE_feature_selection(data)

In [76]:
def xgboost_feature_selection(X,y):
    import xgboost as xgb
    model = xgb.XGBRegressor()
    model.fit(X, y)
    importance = model.feature_importances_
    indices = np.argsort(importance)[::-1]
    return X.columns[indices].tolist()

In [1]:
import xgboost as xgb

In [13]:
import xgboost as xgb
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

def xgboost_feature_selection(X,y, number_of_features = 10):
    model = xgb.XGBRegressor()
    model.fit(X, y)
    importance = model.feature_importances_
    indices = np.argsort(importance)[::-1]
    return X.columns[indices][:number_of_features].tolist()

In [14]:
xgboost_feature_selection(data.drop(columns='marg'), data['marg'])

['feat_82',
 'feat_6',
 'feat_36',
 'feat_74',
 'feat_24',
 'feat_35',
 'feat_22',
 'feat_37',
 'feat_61',
 'feat_33']

In [15]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors

def relief_algorithm(X, y, n_features_to_select):
    # Konwersja DataFrame i Series do numpy array
    X = X.values
    y = y.values
    
    # Inicjalizacja wagi cech
    feature_scores = np.zeros(X.shape[1])
    
    # Instancja NearestNeighbors do znajdowania najbliższych sąsiadów
    nn = NearestNeighbors(n_neighbors=2).fit(X)
    
    # Główna pętla algorytmu Relief
    for index, instance in enumerate(X):
        # Znajdowanie najbliższych sąsiadów (1 z tej samej klasy i 1 z innej)
        _, neighbors = nn.kneighbors([instance])
        hit_index = neighbors[0][0] if y[neighbors[0][0]] == y[index] else neighbors[0][1]
        miss_index = neighbors[0][1] if y[neighbors[0][1]] != y[index] else neighbors[0][0]
        
        # Obliczenie różnicy między instancją a hit i miss
        hit_diff = np.abs(instance - X[hit_index])
        miss_diff = np.abs(instance - X[miss_index])
        
        # Aktualizacja wagi cech
        feature_scores += -hit_diff if y[hit_index] == y[index] else hit_diff
        feature_scores += miss_diff if y[miss_index] != y[index] else -miss_diff
    
    # Normalizacja wyników przez liczbę instancji
    feature_scores /= X.shape[0]
    
    # Wybór najważniejszych cech
    important_indices = np.argsort(-feature_scores)[:n_features_to_select]
    return important_indices

# Użycie funkcji
# df to DataFrame, y to Series, np. df.drop('target', axis=1), df['target']
# n_features_to_select to liczba cech, które chcemy wybrać
# important_features = relief_algorithm(df, df['target'], 5)
# print("Selected feature indices:", important_features)

In [16]:
relief_algorithm(data.drop(columns='marg'), data['marg'], 10)

array([ 9,  2, 64,  8, 66,  7, 30, 28, 50, 14], dtype=int64)

In [18]:
data.iloc[:,[ 9,  2, 64,  8, 66,  7, 30, 28, 50, 14]]

,feat_9,feat_2,feat_64,feat_8,feat_66,feat_7,feat_30,feat_28,feat_50,feat_14
datetime,,,,,,,,,,
2022-01-01 00:00:00+01:00,10389.003405,14946.845019,0.0,4503.082418,8428.0,0.000000,433.0,700.0,1404.0,870.0
2022-01-01 01:00:00+01:00,9829.394903,14243.407120,0.0,4361.306210,9105.0,0.000000,433.0,700.0,1404.0,870.0
2022-01-01 02:00:00+01:00,9471.930284,13722.977780,0.0,4185.773762,9378.0,0.000000,443.0,700.0,1404.0,870.0
2022-01-01 03:00:00+01:00,9773.339869,13726.786816,0.0,3908.972594,9800.0,0.000000,443.0,700.0,1444.0,870.0
2022-01-01 04:00:00+01:00,9985.306606,13827.919086,0.0,3800.952626,10050.0,0.000000,454.0,700.0,1444.0,870.0
...,...,...,...,...,...,...,...,...,...,...
2024-04-14 12:00:00+02:00,1846.798231,14465.680472,0.0,7628.633749,16702.0,4990.248492,877.0,1960.0,1444.0,2500.0
2024-04-14 13:00:00+02:00,1642.527992,14300.580307,0.0,7697.715814,16644.0,4960.336501,866.0,1940.0,1444.0,2500.0
2024-04-14 14:00:00+02:00,1398.646497,13776.317687,0.0,7648.371481,16078.0,4729.299709,877.0,1940.0,1444.0,2500.0
2024-04-14 15:00:00+02:00,2024.623127,14167.633878,0.0,7618.764882,15395.0,4524.245869,877.0,1950.0,1444.0,2500.0
2024-04-14 16:00:00+02:00,3258.400467,14386.388004,0.0,7500.338485,13822.0,3627.649052,887.0,1960.0,1444.0,2500.0

In [ ]:
# dla nowych metod pokaz jakie sa zaleznosci miedzy zlozonoscia modelu a czasem wykonania